feat(cli): Add a basic cli to manage nodes
RustineCI/rustinecore pull request #3
Opened 2022-05-29 20:11 UTC by Pepiloto

The cli handle the creation, listing, deletion and renaming of nodes.

2022-05-29 20:23 UTC, n0no123 approved these changes
LGTM!

2022-05-30 17:53 UTC, Jordan-B1 commented on src/nodes/mod.rs
> +        println!("No node found, create nodes before listing them.");
Hey, i maybe am just a lil bit "tatillon"
But this sentence seems like an error but for me it shouldn't be one. What do you think about something more like "List empty" or "No node found, let's create some !"
Because the user CAN in fact list an empty list :)

2022-05-30 17:53 UTC, Jordan-B1 commented on src/cli.rs
> +        _ => println!("Not a node command"),
Here we use a match but why don't we use a global associative array or a map instead ? Because if we had more commands, it would be more readable don't u think ? Scalability should be our master word.
Create a map would allow us to have less "functional code" and more "configuration code" and as we want to create some open source, we should prefer something that can be changed easily (edit a global variable) rather than something that need the Dev to read more code

2022-06-08 20:29 UTC, Pepiloto commented on src/nodes/mod.rs
> +        println!("No node found, create nodes before listing them.");
I changed the sentence, tell me if it's good

2022-06-08 21:00 UTC, ArthurS1 requested changes

2022-06-08 21:00 UTC, ArthurS1 commented on src/cli.rs
> +        _ => println!("Something else than a right command"),
Wrong command ?

2022-07-01 12:33 UTC, ArthurS1 approved these changes

2022-07-18 09:11 UTC, n0no123 reviewed
Not a big fan of the current phrasing.

2022-07-18 09:11 UTC, n0no123 commented on .gitignore
> +.idea
This should not be in the .gitignore of the project.

2022-07-18 09:11 UTC, n0no123 commented on src/cli.rs
> +/// node_list (Vec<Node>): The list of the Nodes
The list of the Nodes -> The Nodes list

2022-07-18 09:11 UTC, n0no123 commented on src/cli.rs
> +/// command (String): The command given by the user
The Command given by the user -> The user command

2022-07-18 09:11 UTC, n0no123 commented on src/cli.rs
> +/// command (std::str::SplitWhitespace): The command given by the user
The Command given by the user -> The user command

2022-07-18 09:11 UTC, n0no123 commented on src/cli.rs
> +/// node_list (Vec<Node>): The list of the Nodes
The list of the Nodes -> The Nodes list

2022-07-18 09:11 UTC, n0no123 commented on src/nodes/mod.rs
> +        println!("No node found, create some to display their informations when listing.");
I find the phrasing disturbing. Maybe try something like : 'No node found, please create one before listing them'.

_PS: I know this is very much like the previous version._

2022-07-18 09:24 UTC, Pepiloto commented on src/nodes/mod.rs
> +        println!("No node found, create some to display their informations when listing.");
I changed it because Jordan said you can list the nodes when you have zero but you should say to the user to create some

2022-07-18 09:24 UTC, Pepiloto commented on .gitignore
> +.idea
Why ?

2022-07-18 09:35 UTC, Pepiloto commented on src/nodes/mod.rs
> +        println!("No node found, create some to display their informations when listing.");
https://github.com/RustineCI/rustinecore/pull/3#discussion_r885008711

2022-10-03 04:52 UTC, merged